### ISSUE TITLE
The front end cannot call the back end interface

### ISSUE THREAD

**Issue by 12-jingran-12** [back9907/Energy#3]
There are not any logs at back-end after front-end call the flask interface @7343700

**Comment by 12-jingran-12** [comment]
Try to method to fix:
1. Delete "http://127.0.0.1" when you call interfaces at the front end
2. When you run flask app: app.run(host='0.0.0.0', port=5001) change the host to the internal address of the google server.
@7343700 you can get the internal address from @back9907

**Comment by 7343700** [comment]
The first method was successfully tested and has now been successfully launched.
