### ISSUE TITLE
The panel control board page loads slowly

### ISSUE THREAD

**Issue by 7343700** [back9907/Energy#5]
I try to search for cities such as galati and shanghai on the main interface, and then enter the panel control board page to load very slowly. When I scale the ploygon down to a very small area it loads fine.

**Comment by 7343700** [comment]
possible reason:
1. The selected area is too large, and loading the array consumes too much memory, resulting in very slow loading
2. The two pages use different map APIs, which makes the API support for other countries limited.
Please find out what is the specific reason @12-jingran-12

**Comment by 12-jingran-12** [comment]
@7343700 your solution documents were uploaded to google drive: https://drive.google.com/drive/folders/1YhVBw9_EBXl-BF7GI6GnyodHWqroIjzl

**Comment by 12-jingran-12** [comment]
> @7343700 your solution documents were uploaded to google drive: https://drive.google.com/drive/folders/1YhVBw9_EBXl-BF7GI6GnyodHWqroIjzl

The Client chose the second plan

**Comment by 7343700** [comment]
Okay, I will give a more detailed technical document this week to explain the specific implementation process and technical details required for Method 2.

**Comment by 12-jingran-12** [comment]
The technical document was uploaded here.
https://drive.google.com/file/d/1sAHEWClAdkzxrGmvDtwy-eMjt8cKL81u/view?usp=share_link

**Comment by 12-jingran-12** [comment]
The development of this bug will pass to group of next semester.
