### ISSUE TITLE
The Apply Loan of the Hydro Mode is not functioanal 

### ISSUE THREAD

**Issue by 12-jingran-12** [back9907/Energy#6]
![image](https://user-images.githubusercontent.com/59268440/234574502-521d2d61-61b3-4c59-bca5-a34b4f80d7fd.png)
The botton highlighted in this image is not functional @7343700

**Comment by 7343700** [comment]
This part is not covered in the previous PRD, so I ignored the function of implementing the button. I will improve this part of the code as soon as possible.
