### ISSUE TITLE
No major bugs in PHES Calculator

### ISSUE THREAD

**Issue by 12-jingran-12** [back9907/Energy#8]
Please be careful to the unit of each attribute, and use python in-build method to compute irr and roi @xie1840

**Comment by xie1840** [comment]
already optimize the algorithm and find the real data of an operating power station for testing the algorithm. the testing result is similar to the calculation result.

**Comment by xie1840** [comment]
@12-jingran-12 upload the first version of back end testing report to google driver, Please check it
